### ISSUE TITLE
GoogleAuthenticator.psm1 generates wrong pin if secret >16 symbols

### ISSUE THREAD

**Issue by nikitinay** [HumanEquivalentUnit/PowerShell-Misc#1]
Hello. I checked with secret lenght >16 and it generates wrong pin.
Could you please take a look?

![image](https://user-images.githubusercontent.com/50340074/82563931-8fdd8500-9b80-11ea-9771-bbfef8251ccd.png)

**Comment by HumanEquivalentUnit** [comment]
Hi @nikitinay, thanks for reporting this 🙂

I can't add a secret with >16 characters to the Google Auth app on my phone; can you tell me how you added it to authy, please?

If I just put in `aaaabbbb` as the "code given by the website" into Authy, it generates different PINs even for short secrets. Where can I create a code for Authy?
